### PR TITLE
Adding website / ifpv download

### PR DESCRIPTION
**Pull request by Aaronsss**
Adding IFPV and website download for csv files

A few other minor tweaks include;
1. gitattributes and gitignore files added
2. tweaked file location so it works on other operating systems
3. some text tweaks

I am still waiting on a few updates to ifpv for a complete test before this is ready to merge but figured its a good idea to add a draft PR to make sure you are happy with the scope of the changes.

### CODE REVIEW

**Comment by L1cardo** [comment]
Looks good! 
I will take a look!

**Comment by L1cardo** [comment]
Also there is an problem when using URL import:

```bash
Attempting to download: https://gh-proxy.com/https://raw.githubusercontent.com/L1cardo/RHtest/main/pilots.csv
Exception via catchLogExceptionsWrapper
Traceback (most recent call last):
  File "/home/pi/RotorHazard/src/server/RHUtils.py", line 299, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/pi/RotorHazard/src/server/eventmanager.py", line 97, in run_handler
    return handler(args)
           ^^^^^^^^^^^^^
  File "/home/pi/RotorHazard/src/server/RHUI.py", line 249, in dispatch_quickbuttons
    btn.fn(btn.args)
  File "/home/pi/RotorHazard/src/server/plugins/pilot_csv_importer/__init__.py", line 76, in import_pilot
    self.download_csv(self._rhapi.db.option("pilot-csv-importer-location"))
  File "/home/pi/RotorHazard/src/server/plugins/pilot_csv_importer/__init__.py", line 68, in download_csv
    download_result = urllib.request.urlretrieve(url, download_location)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/urllib/request.py", line 251, in urlretrieve
    tfp = open(filename, 'wb')
          ^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: './plugins/pilot_csv_importer/downloaded/piots.csv'
```

**Comment by Aaronsss** [comment]
Does the downloaded folder already exist for you @L1cardo ?

Also are you running this on a pi?

**Comment by L1cardo** [comment]
No, the folder doesn't exit.
I am testing on a Pi4

**Comment by Aaronsss** [comment]
I have added it to the repo. Can you update and try again?

**Comment by L1cardo** [comment]
Merged, thank you for the contribution!

**Pull request merged**
